In [1]:
import os
import pickle
import shutil
import warnings
import random as r
import numpy as np
import pandas as pd
import seaborn as sns

# Matplotlib Imports
import matplotlib  
import matplotlib.pyplot as plt
matplotlib.use(u'nbAgg')
%matplotlib inline

from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix

In [2]:
data_size_byte = pd.read_csv("file_size.csv", sep=",", index_col=False)

In [3]:
byte_features = pd.read_csv("result1.csv", sep=",", index_col=False)
byte_features['ID']  = byte_features['ID'].str.split('.').str[0]
byte_features.head()

ID       0     1     2     3     4     5     6     7  \
0  01azqd4InC7m9JpocGv5  601905  3905  2816  3832  3345  3242  3650  3201   
1  01IsoiSMh5gxyDYTl4CB   39755  8337  7249  7186  8663  6844  8420  7589   
2  01jsnpXSAlgw6aPeDxrU   93506  9542  2568  2438  8925  9330  9007  2342   
3  01kcPWA9K2BOxQeS5Rju   21091  1213   726   817  1257   625   550   523   
4  01SuzwMJEIXsK7A8dQbl   19764   710   302   433   559   410   262   249   

      8  ...    f7    f8    f9    fa    fb    fc    fd     fe     ff     ??  
0  2965  ...  2804  3687  3101  3211  3097  2758  3099   2759   5753   1824  
1  9291  ...   451  6536   439   281   302  7639   518  17001  54902   8588  
2  9107  ...  2325  2358  2242  2885  2863  2471  2786   2680  49144    468  
3  1078  ...   478   873   485   462   516  1133   471    761   7998  13940  
4   422  ...   847   947   350   209   239   653   221    242   2199   9008  

[5 rows x 258 columns]

In [4]:
result = pd.merge(byte_features, data_size_byte, on = 'ID', how = 'left')
result.head()

ID       0     1     2     3     4     5     6     7  \
0  01azqd4InC7m9JpocGv5  601905  3905  2816  3832  3345  3242  3650  3201   
1  01IsoiSMh5gxyDYTl4CB   39755  8337  7249  7186  8663  6844  8420  7589   
2  01jsnpXSAlgw6aPeDxrU   93506  9542  2568  2438  8925  9330  9007  2342   
3  01kcPWA9K2BOxQeS5Rju   21091  1213   726   817  1257   625   550   523   
4  01SuzwMJEIXsK7A8dQbl   19764   710   302   433   559   410   262   249   

      8  ...    f9    fa    fb    fc    fd     fe     ff     ??      size  \
0  2965  ...  3101  3211  3097  2758  3099   2759   5753   1824  5.012695   
1  9291  ...   439   281   302  7639   518  17001  54902   8588  6.556152   
2  9107  ...  2242  2885  2863  2471  2786   2680  49144    468  4.602051   
3  1078  ...   485   462   516  1133   471    761   7998  13940  0.679688   
4   422  ...   350   209   239   653   221    242   2199   9008  0.438965   

   Class  
0      9  
1      2  
2      9  
3      1  
4      8  

[5 rows x 260 columns]

In [5]:
def normalize(df):
    result1 = df.copy()
    for feature_name in df.columns:
        if (str(feature_name) != str('ID') and str(feature_name)!=str('Class')):
            max_value = df[feature_name].max()
            min_value = df[feature_name].min()
            result1[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result1
result = normalize(result)

In [11]:
from keras.utils.np_utils import to_categorical
cat_y = to_categorical(y)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(8148, 258)
(8148,)
(2717, 258)
(2717,)


In [22]:
from sklearn.tree import DecisionTreeClassifier
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)

accuracy = dtree_model.score(X_test, y_test)
print(accuracy)
 
# creating a confusion matrix
cm = confusion_matrix(y_test, dtree_predictions)
print(cm)

0.5852042694147958
[[372  22   0   0   1   0   0   0   0]
 [141 468   0   0   0   0   0   0   0]
 [  2   0 747   0   0   0   0   0   0]
 [104   0   0   0   0   0   0   0   0]
 [ 10   0   0   0   3   0   0   0   0]
 [189   0   0   0   0   0   0   0   0]
 [100   7   0   0   0   0   0   0   0]
 [310   0   1   0   0   0   0   0   0]
 [236   4   0   0   0   0   0   0   0]]


In [23]:
from sklearn.svm import SVC
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train)
svm_predictions = svm_model_linear.predict(X_test)
 
# model accuracy for X_test 
accuracy = svm_model_linear.score(X_test, y_test)
print(accuracy)
 
# creating a confusion matrix
cm = confusion_matrix(y_test, svm_predictions)
print(cm)

0.7526683842473316
[[175   7   1   0   0   1   2 207   2]
 [ 48 530   0   0   0  15   2  11   3]
 [  0   0 747   0   0   2   0   0   0]
 [  2   0   0   0   0   9   0  93   0]
 [  1   0   0   0   0   0   7   5   0]
 [  9   0   2   0   0 116   0  62   0]
 [  5   0   0   0   0   4  98   0   0]
 [ 15   0   2   0   0   5   0 289   0]
 [  2   3   0   0   0  14   0 131  90]]


In [24]:
# training a KNN classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train)
 
# accuracy on X_test
accuracy = knn.score(X_test, y_test)
print(accuracy)
 
# creating a confusion matrix
knn_predictions = knn.predict(X_test)
cm = confusion_matrix(y_test, knn_predictions)
print(cm)

0.9293338240706662
[[370   0   2   0   2   7   0   3  11]
 [ 43 531   0   0   0  16   3   3  13]
 [  0   0 748   0   0   0   0   1   0]
 [  2   0   0 101   0   1   0   0   0]
 [  3   0   0   1   8   0   0   1   0]
 [  7   0   1   3   0 172   0   4   2]
 [  6   2   0   0   0   4  91   0   4]
 [ 17   0   2   0   1   7   0 280   4]
 [  7   5   0   0   0   2   0   2 224]]


In [25]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train, y_train)
gnb_predictions = gnb.predict(X_test)
 
# accuracy on X_test
accuracy = gnb.score(X_test, y_test)
print(accuracy)
 
# creating a confusion matrix
cm = confusion_matrix(y_test, gnb_predictions)
print(cm)

0.6687523003312477
[[100   5   0  79   2  11   2 186  10]
 [ 38 502   0   0   0   0   0  18  51]
 [  0   0 670   0   0   0   0   0  79]
 [  0   0   0  52  31   1   0  20   0]
 [  0   0   0   0  12   0   0   1   0]
 [  0   0   1  15  14 125   0  34   0]
 [  2  10   0   0   0   5   2  85   3]
 [  7   0   3  11   3   4   0 281   2]
 [ 17  27   0  21   0   9   4  89  73]]
